### ISSUE TITLE
常用gulp插件介绍(一) | 

### ISSUE THREAD

**Issue by PinkyJie** [PinkyJie/pinkyjie.github.com#11]
http://pinkyjie.com/2015/08/02/commonly-used-gulp-plugins-part-1/

**Comment by xianghongai** [comment]
极不建议采用“gulp-useref”，它会真的去合并标记内的引用文件到物理文件中！这极其不合理，我们在src中是分模块编码，在dist出来是扁平的页面，这里文件路径会有差异，并且，涉及到ecmascript新语法需要babel打包，这个插件显得极不专业。推荐采用“gulp-html-replace”。只是字符上处理引用，不理会是否真的有对应文件。

**Comment by PinkyJie** [comment]
@xianghongai 这是很老的文章了，现在都直接webpack了吧

**Comment by xianghongai** [comment]
在逼乎看统计全球还有近50%的开发者用gulp，毕竟并不是所有项目都SPA。:-)
