### ISSUE TITLE
最近的海外面试（前端）经历 | 进击的马斯特

### ISSUE THREAD

**Issue by PinkyJie** [PinkyJie/pinkyjie.github.com#2]
http://pinkyjie.com/2017/02/21/recent-overseas-interview-experiences/

**Comment by PinkyJie** [comment]
以前的评论都丢了！

**Comment by kreja** [comment]
好多算法题啊……请问博主，是平时都在练英语的吗？感觉听还好，但是说就很尴尬了……

**Comment by PinkyJie** [comment]
@kreja 在外企呆了两年老开会，锻炼了下

**Comment by caozilu** [comment]
也是从上海去国外的前辈啊 虽然觉得自己也有能力去国外 去没有一颗去国外的心

**Comment by harryge00** [comment]
楼主能内推吗 ？ 有devops职位不

**Comment by PinkyJie** [comment]
@harryge00 去年四月起澳洲政策变动很大，现在我司已经不从海外招人了。。。

**Comment by JInchengLiuAu** [comment]
所以大佬最后去了iress吗？那边福利怎么样？

**Comment by PinkyJie** [comment]
@JInchengLiuAu 大家的评价就是，除了工资不高其他都挺好的。。。
