### ISSUE TITLE
浅谈协方差矩阵 | 进击的马斯特

### ISSUE THREAD

**Issue by PinkyJie** [PinkyJie/pinkyjie.github.com#53]
http://pinkyjie.com/2010/08/31/covariance/

**Comment by clouduan** [comment]
受用

**Comment by hqzzlo** [comment]
写得非常通俗易懂啊~由浅入深，恰到好处。非常感谢！

**Comment by ruanxuyi** [comment]
感谢！

**Comment by fthou** [comment]
写得很棒，非常感谢！可是根据定义，紧挨着’总结‘ 前边的代码
C = (X'*X)./(size(X,1)-1); 
不应该是  C = (X*X')./(size(X,1)-1)吗？

**Comment by PinkyJie** [comment]
@fthou 抱歉，毕业好多年了，不太记得了。。。

**Comment by fthou** [comment]
@PinkyJie  嗯嗯，等有空了我再研究一下。非常感谢！

**Comment by Becomebright** [comment]
十分感谢，讲的很清楚

**Comment by tesala** [comment]
通俗易懂，感谢~

**Comment by jiangleidhr** [comment]
@fthou C = (X'*X)./(size(X,1)-1);是对的，确实是用转置乘以自身。当列是维度的时候，协方差矩阵保留列，应该是转置后的矩阵乘以自身。@PinkyJie 在update中的说明写反了。
